### ISSUE TITLE
Sporadic "ffmpeg_svt_hevc" test failure 

### ISSUE THREAD

**Issue by SDxKeeper** [OpenVisualCloud/Dockerfiles#105]
Following test fails sporadically in travis on random centos ffmpeg images:

/mnt/ffmpeg_svt_hevc.sh: line 4:     9 Segmentation fault      (core dumped) ffmpeg -f rawvideo -vcodec rawvideo -s 320x240 -r 30 -pix_fmt yuv420p -i test.yuv -c:v libsvt_hevc -y test.mp4
 6/10 Test  #6: test_xeon_ffmpeg_centos75_ffmpeg_svt_hevc ...***Failed    1.88 sec

Log from master:
https://api.travis-ci.com/v3/job/199781932/log.txt
Log from pull request:
https://api.travis-ci.com/v3/job/199645510/log.txt

**Comment by jhou5** [comment]
Cannot reproduce in local machine, thus the test failure is not related to the product itself, instead it should be related to Travis CI enviornment. Would check Travis CI entionrment then.

**Comment by dpatel257** [comment]
Same, not see on local machine
