### ISSUE TITLE
ffmpeg SVT-AV1 plugin bug

### ISSUE THREAD

**Issue by dpatel257** [OpenVisualCloud/Dockerfiles#118]
ffmpeg -i travel6.mp4 -c:v libsvt_av1 -y travel6_av1.mp4
ffprobe -v error -show_streams travel6_av1.mp4

Probing errors into this:
root@6298ae4ea5e2:/home# x
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55ededd3fd40] Empty AV1 Codec Configuration Box
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55ededd3fd40] error reading header
travel6_av1.mp4: Invalid data found when processing input

**Comment by jhou5** [comment]
Pull request: https://github.com/OpenVisualCloud/SVT-AV1/pull/286 fixed this issue

**Comment by jhou5** [comment]
OpenVisualCloud/SVT-AV1#286 is merged into master, wait for SVT-AV1 v0.6 tag to integrate into dockerfiles

**Comment by jhou5** [comment]
The issue is fixed with PR #168.
