### ISSUE TITLE
Upgrade to Gstreamer 1.16

### ISSUE THREAD

**Issue by g-schnaubelt-Intel** [OpenVisualCloud/Dockerfiles#122]
https://gstreamer.freedesktop.org/releases/1.16/

Version 1.16 brings performance improvements and new features.

**Comment by jhou5** [comment]
@g-schnaubelt-Intel have you planned to submit PR for this upgrade?

**Comment by g-schnaubelt-Intel** [comment]
@fkhoshne Was working on this and ran into issues with the tests not working after the directory restructuring. I see you have a recent commit that mentions fixes for ctest so I think the gst-1.16 work can progress now.

**Comment by jhou5** [comment]
Yes. I fixed ctest doesn't work issue and hope it is the same issue you mentioned.

**Comment by fkhoshne** [comment]
#141 Created a Pull Request to update Gstreamer and associated plugins to version 1.16.0.

**Comment by fkhoshne** [comment]
Gstreamer and associated packages have been updated to 1.16.0
