### ISSUE TITLE
Case "CPU=Xeon buildOS=centos-7.6 usage=service imageName=owt" always failed!

### ISSUE THREAD

**Issue by linxie47** [OpenVisualCloud/Dockerfiles#151]
Logs:

[32mFollowing targets will be built:[0m
 video-mixer-sw 
 video-transcoder-sw 
 video-analyzer-sw 
 internal-io 
 logger 
 media-frame-multicaster 
 audio 
 webrtc 
 avstream 
 sip 
[32mBuilding addon[0m - video-mixer-sw
make: Entering directory `/home/owt-server/source/agent/video/videoMixer/videoMixer_sw/build'
  CXX(target) Release/obj.target/videoMixer-sw/../addon.o
  CXX(target) Release/obj.target/videoMixer-sw/../VideoMixerWrapper.o
  CXX(target) Release/obj.target/videoMixer-sw/../SoftVideoCompositor.o
  CXX(target) Release/obj.target/videoMixer-sw/../VideoMixer.o
[91mIn file included from ../../VideoFrameMixerImpl.h:29:0,
                 from ../../VideoMixer.cpp:9:
/home/owt-server/source/core/owt_base/SVTHEVCEncoder.h:19:28: fatal error: svt-hevc/EbApi.h: No such file or directory
 #include "svt-hevc/EbApi.h"
                            ^
compilation terminated.
[0m[91mmake: *** [Release/obj.target/videoMixer-sw/../VideoMixer.o] Error 1
make: *** Waiting for unfinished jobs....
[0mmake: Leaving directory `/home/owt-server/source/agent/video/videoMixer/videoMixer_sw/build'
[91mgyp[0m[91m ERR! build error 
[0m[91mgyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:190:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System[0m[91m Linux 4.15.0-1028-gcp
gyp[0m[91m ERR! command[0m[91m "/usr/bin/node" "/usr/bin/node-gyp" "rebuild" "-j" "2" "--loglevel=error"
[0m[91mgyp ERR! cwd[0m[91m /home/owt-server/source/agent/video/videoMixer/videoMixer_sw
gyp[0m[91m ERR! node -v v8.15.0
[0m[91mgyp ERR![0m[91m node-gyp -v v5.0.0
[0m[91mgyp [0m[91mERR! not ok 
[0m[91mchild_process.js:650
    throw err;
    ^

Error: Command failed: node-gyp rebuild -j 2 --loglevel=error
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at buildTarget (/home/owt-server/scripts/build.js:128:5)
    at buildList.map (/home/owt-server/scripts/build.js:155:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/owt-server/scripts/build.js:154:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

**Comment by fkhoshne** [comment]
Created a pull request to fix this issue. Appears to have been a missing template.

**Comment by dpatel257** [comment]
Merged in master
