### ISSUE TITLE
Request to enable the drawtext filter in the ffmpeg build.

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Dockerfiles#16]

**Comment by djie1** [comment]
drawtext filter is enabled for FFmpeg ("--enable-libfreetype") in the "*-dev" images. Does this meet the requirements?

**Comment by jhou5** [comment]
If size is not too big, it would be best to enable also in the deployment images: ffmpeg and dldt-ffmpeg.

**Comment by djie1** [comment]
PR#78, take image "xeon-ubuntu1604-ffmpeg" as example, size increases from 183M to 192M

**Comment by dpatel257** [comment]
merged in master
