### ISSUE TITLE
dldt by default download its own prebuilt OpenCV

### ISSUE THREAD

**Issue by umed** [OpenVisualCloud/Dockerfiles#180]
According to instructions from here [README: use custom opencv](https://github.com/opencv/dldt/blob/2019/inference-engine/README.md#use-custom-opencv-builds-for-inference-engine)

Should be:

1. exported environment variable to `OpenCV_DIR` which points to OpenCVConfig.cmake
2. specified `-DENABLE_OPENCV=OFF` for cmake configuration

**Comment by fkhoshne** [comment]
This issue has been resolved with commit [d27d2688933f2ec3838f879bc9725d0e8b3a953f](https://github.com/OpenVisualCloud/Dockerfiles/commit/d27d2688933f2ec3838f879bc9725d0e8b3a953f)
