### ISSUE TITLE
Avoid usage of 'make -j<number>' instead do 'make -j $(nproc)'

### ISSUE THREAD

**Issue by umed** [OpenVisualCloud/Dockerfiles#19]
For example, we are building some dockerfile with dldt (you can see example below) on a PC with 4 cores and not enough RAM this build process will be endless (it will hang).

```dockerfile
RUN git clone -b ${DLDT_VER} ${DLDT_REPO}; \
    cd dldt; \
    git submodule init; \
...
    make -j16; \
    rm -rf ../bin/intel64/Release/lib/libgtest*; \
```

We can take into account number of cores by using `nproc` then above step will look like this:

```dockerfile
RUN git clone -b ${DLDT_VER} ${DLDT_REPO}; \
    cd dldt; \
    git submodule init; \
...
    make -j $(nproc); \
    rm -rf ../bin/intel64/Release/lib/libgtest*; \
```

**Comment by xwu2git** [comment]
This may be dangerous. Some Xeon have 80+ logical processors.

**Comment by umed** [comment]
@xwu2git probably, we can add constant  `THREADS_COUNT` and pass it as number of threads for make.

**Comment by umed** [comment]
However, @xwu2git are you going to build images on Xeon with 80+ cores?

**Comment by xwu2git** [comment]
I think for build purpose, making it 8-16 is good enough. Too many does not really give better performance.

**Comment by umed** [comment]
I'm agree, but another problem is reproducible on PC with 4 cores and small amount of RAM. When you set 16 threads gcc starts freezing PC.

**Comment by xwu2git** [comment]
There is no need to generalize. No all projects can compile 16 or more in parallel and choke PC. For a few that do, can we set a limit with shell commands? I don't like to set a lot of env variables. hard to track.

**Comment by umed** [comment]
I didn't find such mechanism. Think we can close this issue.
