### ISSUE TITLE
E3 README.md issue

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#235]
For the documentation -
===========================================
Modify /etc/lightdm/lightdm.conf and restart the service

cat /etc/lightdm/lightdm.conf
[SeatDefaults]
autologin-user=<SYSTEM_USER_NAME>

sudo systemctl restart ligthdm
===========================================

The correct path is /etc/lightdm/lightdm.conf.d/lightdm.conf instead of /etc/lightdm/lightdm.conf? i tried on ubuntu16.04

**Comment by dpatel257** [comment]
I think both works. As long as they are under /etc/lightdm/ and end with .conf they work

**Comment by jhou5** [comment]
I tried and verified, both works. Thanks and would close this issue.
