### ISSUE TITLE
Please re-evaluate the instruction to avoid sudo.

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Dockerfiles#27]
Please see this article: https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/

**Comment by umed** [comment]
it's known security issue. We can update instruction and mention this issue and add that user can add himself to docker group on non-production systems, but should run build scripts by using `sudo` on the systems where he is not in the docker group. Is it fine?

**Comment by xwu2git** [comment]
We use cmake to build. Use sudo to run cmake? That will mess up with a lot of stuff.
I think we need to write instructions separately for Ubuntu and CentOS if needed, but do need to cover both host OS'es.

**Comment by xwu2git** [comment]
Reread the article. I do think having sudo back is a better security measure. 
Let's not suggest practices that have known security issues.

**Comment by umed** [comment]
@xwu2git we can revert changes for now then

**Comment by xwu2git** [comment]
please do.

**Comment by dpatel257** [comment]
Reverted on 'master'
