### ISSUE TITLE
missing the openvino share folder in the dev image

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Dockerfiles#277]
InferenceEngine_DIR=/opt/intel/openvino/deployment_tools/inference_engine/share

This folder does not exist in the dev image.

**Comment by xwu2git** [comment]
This is the VCAC-A dev image. 

Additionally, there is -DDISABLE_VAAPI=ON in the Dockerfile. This option should be removed.

**Comment by xwu2git** [comment]
Include & static libraries are all missing.

**Comment by dpatel257** [comment]
> Additionally, there is -DDISABLE_VAAPI=ON in the Dockerfile. This option should be removed.

Yes, there is no such option as 'DISABLE_VAAPI'. It is 'HAVE_VAAPI'

**Comment by xwu2git** [comment]
Have static libraries been restored in the dev image?

**Comment by dpatel257** [comment]
Yes, this was fixed with #293
