### ISSUE TITLE
mp3lame repo is not stable to download recently, issue found from Mar 4th, 2019

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#29]
**Logs shown as below:** 

Step 21/63 : RUN wget -O - ${MP3LAME_REPO} | tar xz;     cd lame-${MP3LAME_VER};     ./configure --prefix="/usr" --libdir=/usr/lib64 --enable-shared --enable-nasm;     make -j8;     make install DESTDIR=/home/build;     make install
 ---> Running in 4e904c50ec63
--2019-03-06 02:49:20--  https://sourceforge.net/projects/lame/files/lame/3.100/lame-3.100.tar.gz
Resolving sourceforge.net (sourceforge.net)... 216.105.38.13
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
Unable to establish SSL connection.
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
/bin/sh: line 0: cd: lame-3.100: No such file or directory
/bin/sh: ./configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
make: *** No rule to make target `install'.  Stop.
The command '/bin/sh -c wget -O - ${MP3LAME_REPO} | tar xz;     cd lame-${MP3LAME_VER};     ./configure --prefix="/usr" --libdir=/usr/lib64 --enable-shared --enable-nasm;     make -j8;     make install DESTDIR=/home/build;     make install' returned a non-zero code: 2
Xeon/centos-7.4/dldt+ffmpeg/CMakeFiles/build_xeon_dldt_ffmpeg_cent74.dir/build.make:57: recipe for target 'Xeon/centos-7.4/dldt+ffmpeg/CMakeFiles/build_xeon_dldt_ffmpeg_cent74' failed
make[2]: *** [Xeon/centos-7.4/dldt+ffmpeg/CMakeFiles/build_xeon_dldt_ffmpeg_cent74] Error 2
CMakeFiles/Makefile2:2079: recipe for target 'Xeon/centos-7.4/dldt+ffmpeg/CMakeFiles/build_xeon_dldt_ffmpeg_cent74.dir/all' failed
make[1]: *** [Xeon/centos-7.4/dldt+ffmpeg/CMakeFiles/build_xeon_dldt_ffmpeg_cent74.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
The command "make" exited with 2.

**Comment by jhou5** [comment]
the issue is gone on Mar 7 with no change, let's keep on monitor it.

**Comment by xwu2git** [comment]
Can we find an alternative source as a backup?

**Comment by dpatel257** [comment]
This is common accross different repos because of their website down time. Need generic solution to fix such failures. Local mirror setup of all packages needed ?

**Comment by xwu2git** [comment]
Is there any limitation on github to cache binary packages?

**Comment by jhou5** [comment]
issue didn't happen later since Mar 7th. Close it.
