### ISSUE TITLE
Working with OpenVINO offline.

### ISSUE THREAD

**Issue by MohannadKassar** [OpenVisualCloud/Dockerfiles#297]
I want to make an application based on Intel EDGE AI openVINO  on my own laptop, how to get all what I need of installation and modifications to do that and run the environment? I got openVINO toolkit, Visual Studio 2019, CMake, and python latest version with the TensorFlow framework. Any one worked with this before?

**Comment by GregRose** [comment]
There are some instructions on how to set up the Smart City Sample on your laptop in the Smart City Sample wiki. This will also set up OpenVINO. Check it out!  https://github.com/OpenVisualCloud/Smart-City-Sample/wiki/Tutorial:-Running-Smart-City-on-a-Windows*-Laptop

**Comment by jhou5** [comment]
No further questions, close it. Feel free to submit new one if you still want to discuss or support.
