### ISSUE TITLE
CI build performance improvement

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#32]
Dockerfiles CI build leverage Travis CI cloud service with a limitation of build time should be <50 mins, what's the opportunity to speed up our dockerfiles build and improve it?

**Comment by xwu2git** [comment]
(1) cache wget & apt-get traffic. 
(2) perform one platform build at a time.

**Comment by 1480c1** [comment]
Can I recommend to do a base image build (One with most of the stuff necessary to build the rest such as a single image for common tools etc), upload, then in the other dockerfiles, point towards that image as the FROM?

**Comment by xwu2git** [comment]
It would be good to avoid dependencies between dockerfiles, as such dependencies will increase the difficulty of using the dockerfiles. The developer will have to find all dependencies (maybe from other directories) and build them all. The design should facilitate the users of the dockerfiles.

**Comment by 1480c1** [comment]
Since this repo binds to certain versions of cmake and automake, and the only times those are updates is when a commit is merged (travis is triggered), I think it would be okay to have a build-tools image for each OS+version. Something like <https://docs.travis-ci.com/user/build-stages/share-docker-image/>.
If it is necessary, the ONBUILD command can be used in the base dockerfiles


This would necessitate either docker-hub or some other docker repo that is publicly accessible.

**Comment by 1480c1** [comment]
I can try to submit an example later, but since I'm not well versed in m4, it might take a while

**Comment by xwu2git** [comment]
Thanks for the suggestion. 1 base image for build is ok. Let's don't try to put everything in it. This image should truly be the "common" build tools. Please revise README to help developers find the dependencies.

**Comment by 1480c1** [comment]
Yea, that's what I mean. \
For example, since the centos-7.4 dockerfiles share build-tools.m4, build a centos-7.4base image with build-tools.m4 and upload to docker-hub, and then do `FROM OpenVisualCloud/dockerfiles:centos7-4base` for the dockerfile.m4

**Comment by fkhoshne** [comment]
I've been playing around with improving build times, not necessarily for CI but if a component is updated to avoid rebuilding layers that don't need to be rebuilt. I have an example Dockerfile here
https://github.com/fkhoshne/Dockerfiles/blob/test_build_change/Xeon/ubuntu-18.04/analytics/gst/Dockerfile.m4

While the example above doesn't save the initial build time, subsequent builds with individual changes would be able to save time. For example, if GST_VER is updated to v1.16.1, the dldt layers would not need to be rebuilt.

While the example above won't save the CI any time, we could use a combination of the example and the docker hub images to save the CI time. Going off of 1480c1's comment to have a base image with common build tools, the example above can be expanded to have a build-tools base, a dependencies base, a gst base, that are all open source components and images pushed to Docker Hub to reduce build times.

**Comment by jhou5** [comment]
Improved the CI efficency through enabling dockerhub as build cache, remove unessary rebuild docker layer and CI time cost is ~10 mins now per image depends on the code change.
Example:
https://travis-ci.com/OpenVisualCloud/Dockerfiles/builds/145484942
