### ISSUE TITLE
DAV1D ffmpeg plugin include into docker

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#33]
Verified it works for DAV1D plugin in  FFMPEG master branch, and waiting for below dependencies ready for integrating it into Dockerfiles -
1. FFMPEG stable release (v4.2).
2. Existing FFMPEG plugin(i.e. SVT) support FFMPEG v4.2

**Comment by xwu2git** [comment]
Now that we have upgraded to ffmpeg 4.2, this can be brought onto schedule.

**Comment by jhou5** [comment]
Yes, would do.

**Comment by jhou5** [comment]
Feature update: remove libaom if DAV1D works

**Comment by jhou5** [comment]
#375
