### ISSUE TITLE
Usage of alternative repo/ARG does not work

### ISSUE THREAD

**Issue by lsandov1** [OpenVisualCloud/Dockerfiles#344]
https://github.com/OpenVisualCloud/Dockerfiles/blob/master/doc/cmake.md#use-alternative-repo

I followed the above instructions but seems that the `export AOM_VER=XXX` is not taken into account by the make commmand. In general, no `ARG` command can be modified on-the-fly or dynamically.

**Comment by xwu2git** [comment]
Strange. The build command does take any _VER args into consideration:
$(env | cut -f1 -d= | grep -E '_(proxy|REPO|VER)$' | sed 's/^/--build-arg /')

**Comment by xwu2git** [comment]
It's in script/build.sh.

**Comment by xwu2git** [comment]
It looks now like a bug in docker build? If specified as docker build --build-arg CMAKE_VER=4567, the ARG values are replaced. If specified as docker build --build-arg CMAKE_VER, the ARG values remain untouched.

**Comment by xwu2git** [comment]
Not quite. This simple Dockerfile works fine. 
FROM ubuntu:18.04
ARG ABC=1.2.3
RUN echo ${ABC}

**Comment by xwu2git** [comment]
It turns out that the sudo build command missed a "-E" to pass the local envs to the sudo environment. 
Fixed with pull request #345.

**Comment by lsandov1** [comment]
Thannks @xwu2git for the quick fix.

**Comment by jhou5** [comment]
OK, close it then. Feel free to submit new issue if having more questions.
