### ISSUE TITLE
Missing openvino tools in the dev image

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Dockerfiles#347]
https://github.com/opencv/open_model_zoo/tree/2018/model_downloader
https://github.com/opencv/dldt/tree/2019/tools

**Comment by jhou5** [comment]
Follow up issues: #348, #349

**Comment by dpatel257** [comment]
Are all #347 #348 #349  for open source vino OR closed source ?

**Comment by jhou5** [comment]
#440
