### ISSUE TITLE
No setupvar.sh script

### ISSUE THREAD

**Issue by dahanhan** [OpenVisualCloud/Dockerfiles#349]
When I was trying to build inference sample with script /home/dldt/inference-engine/samples, an error reports:

```
Setting environment variables for building samples...
Error: Failed to set the environment variables automatically. To fix, run the following command:
source <INSTALL_DIR>/bin/setupvars.sh
where INSTALL_DIR is the OpenVINO installation directory.
```
It's necessary to provide a setupvars.sh to give an easy way to set environment variables. We can find this file from intel distributed package. I've attached the file of OpenVINO R3.
[setupvars.zip](https://github.com/OpenVisualCloud/Dockerfiles/files/4088818/setupvars.zip)

**Comment by xwu2git** [comment]
All env variables are supposed to set already in the docker image. You don’t need to manually run the script.

**Comment by dahanhan** [comment]
It looks env variables are not fully set for building samples. The script is just for reference and docker image should be aligned with the env setup script.

**Comment by dpatel257** [comment]
Issue no longer producible on DLDT 2020.1. Closing Issue
