### ISSUE TITLE
protobuf in dldt-ie.m4

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Dockerfiles#357]
(1) The code is not from a released tag.
(2) The installation is not to /usr/local/lib.

**Comment by xwu2git** [comment]
Also, protobuf seems to be installed multiple times in dldt-ie.m4.
Once explicitly, the other time part of pip install requirements.

**Comment by xwu2git** [comment]
There is another one in opencv.m4.

**Comment by dpatel257** [comment]
> There is another one in opencv.m4.

@xwu2git Couldn't find the one in opencv.m4. Is this comment still relevant?

**Comment by jhou5** [comment]
#442
