### ISSUE TITLE
Inconsistent librdkafka

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Dockerfiles#358]
Multiple installations templates: 0.11.6 in librdkafka.m4 and again embeded 1.0.0 in dldt-ie.m4.

**Comment by dpatel257** [comment]
one in librdkafka.m4
*one in gstreamer-videoanalytics.m4

Dockerfiles affected:
Xeon/centos-7.4/analytics/dev/Dockerfile.m4
Xeon/centos-7.5/analytics/dev/Dockerfile.m4
Xeon/centos-7.6/analytics/dev/Dockerfile.m4
XeonE3/centos-7.4/analytics/dev/Dockerfile.m4
XeonE3/centos-7.5/analytics/dev/Dockerfile.m4
XeonE3/centos-7.6/analytics/dev/Dockerfile.m4
XeonE3/ubuntu-18.04/analytics/dev/Dockerfile.m4
Xeon/ubuntu-18.04/analytics/dev/Dockerfile.m4

**Comment by jhou5** [comment]
#452
