### ISSUE TITLE
Investigate XeonE3 vs VCACA images for passing devices

### ISSUE THREAD

**Issue by dpatel257** [OpenVisualCloud/Dockerfiles#408]
VCAC-A happily works just by having root-privileged mode to it. Try that on XeonE3 vaapi moduels. E3 modules needs lot of manual setup, which shouldnt be the case.
privileged mode OR there is more to it?

**Comment by dpatel257** [comment]
CentOS image do not work out of the box, without the host setup.
Need support from gstreamer-videoanalytics .

**Comment by l1yulong** [comment]
No longer support VCACA from v23.06
