### ISSUE TITLE
Dockerfiles v1.0 release

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#42]
Dockerfiles v1.0 release is planned by End of March, 2019

Code freeze time: 27, Mar, 2019

**Comment by umed** [comment]
hi @jhou5 ,

I created milestone, you can do the same for next release and link issues to milestone. I think it's more convenient way.

**Comment by jhou5** [comment]
@umed, It is good sharing. Thanks a million.
