### ISSUE TITLE
VCAC-A Dockerfile compile failed on ubuntu 18.04

### ISSUE THREAD

**Issue by linxie47** [OpenVisualCloud/Dockerfiles#441]
The media driver failed to compile on ubuntu 18.04.

Log is as below:

Scanning dependencies of target iHD_drv_video_OBJ
[ 30%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_array.cpp.o
[ 30%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_buffer_rt.cpp.o
[ 31%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_state_buffer.cpp.o
[ 31%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_def.cpp.o
[ 31%] Building CXX object media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_device_rt.cpp.o
[91mcc1plus: error: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++ [-Werror]
[0m[91mcc1plus: error: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++ [-Werror]
cc1plus: error: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++ [-Werror]
[0m[91mcc1plus: error: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++ [-Werror]
[0m[91mcc1plus: error: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++ [-Werror]
[0m[91mcc1plus: all warnings being treated as errors
[0mmedia_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:101: recipe for target 'media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_def.cpp.o' failed
[91mmake[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_def.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[0m[91mcc1plus: all warnings being treated as errors
[0m[91mcc1plus: all warnings being treated as errors
[0m[91mmake[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_array.cpp.o] Error 1
[0mmedia_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:62: recipe for target 'media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_array.cpp.o' failed
[91mmake[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_state_buffer.cpp.o] Error 1
[0mmedia_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:88: recipe for target 'media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_state_buffer.cpp.o' failed
[91mcc1plus: all warnings being treated as errors
[0mmedia_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:75: recipe for target 'media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_buffer_rt.cpp.o' failed
[91mmake[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_buffer_rt.cpp.o] Error 1
[0m[91mcc1plus: all warnings being treated as errors
[0m[91mmake[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_device_rt.cpp.o] Error 1
[0mmedia_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:114: recipe for target 'media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_device_rt.cpp.o' failed
CMakeFiles/Makefile2:172: recipe for target 'media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/all' failed
[91mmake[1]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[0m[ 31%] Linking CXX executable GMMULT
[ 31%] Built target GMMULT
Makefile:151: recipe for target 'all' failed
[91mmake: *** [all] Error 2

**Comment by jhou5** [comment]
The issue is introduced by Ubuntu base image upgrade to gcc 7.5.0 recently. Would submit a PR to fix the error soon.

**Comment by jhou5** [comment]
#443
