### ISSUE TITLE
CDN patch v0.3 doen't work with SVT AV1 v0.8.2 release 

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#463]
Step 57/74 : RUN git clone ${SVT_AV1_REPO} &&     cd SVT-AV1 &&     git checkout ${SVT_AV1_VER} &&     find ${SVT_AV1_PATCHES_PATH}/SVT-AV1_patches -type f -name '*.patch' -print0 | sort -z | xargs -t -0 -n 1 patch -p1 -i &&     cd Build/linux &&     mkdir -p ../../Bin/Release &&     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DCMAKE_ASM_NASM_COMPILER=yasm ../.. &&     make -j8 &&     make install DESTDIR=/home/build &&     make install
 ---> Running in 51a5d02c6f1f
Cloning into 'SVT-AV1'...
Note: checking out 'v0.8.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 26938b09 Bump revision and update CHANGELOG.md (#1214)
patch -p1 -i /home/CDN-0.3/SVT-AV1_patches/0001-Add-the-thread-count-parameter-support.patch
patching file Config/Sample.cfg
Hunk #1 FAILED at 80.
1 out of 1 hunk FAILED -- saving rejects to file Config/Sample.cfg.rej
patching file Source/API/EbSvtAv1Enc.h
Hunk #1 succeeded at 20 with fuzz 2 (offset 2 lines).
Hunk #2 succeeded at 555 (offset 57 lines).
patching file Source/App/EncApp/EbAppConfig.c
Hunk #1 succeeded at 154 (offset 16 lines).
Hunk #2 succeeded at 665 (offset 99 lines).
Hunk #3 succeeded at 1367 (offset 597 lines).
Hunk #4 succeeded at 1523 (offset 680 lines).
patching file Source/App/EncApp/EbAppConfig.h
Hunk #1 succeeded at 453 (offset 29 lines).
patching file Source/App/EncApp/EbAppContext.c
Hunk #1 succeeded at 192 (offset 6 lines).
patching file Source/Lib/Encoder/Globals/EbEncHandle.c
Hunk #1 succeeded at 392 with fuzz 1 (offset 4 lines).
Hunk #2 succeeded at 417 (offset 4 lines).
Hunk #3 succeeded at 635 (offset 22 lines).
Hunk #4 succeeded at 658 (offset 22 lines).
patching file ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
Hunk #9 FAILED at 150.
1 out of 13 hunks FAILED -- saving rejects to file ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch.rej
patching file ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
Hunk #9 FAILED at 152.
1 out of 13 hunks FAILED -- saving rejects to file ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch.rej
The command '/bin/sh -c git clone ${SVT_AV1_REPO} &&     cd SVT-AV1 &&     git checkout ${SVT_AV1_VER} &&     find ${SVT_AV1_PATCHES_PATH}/SVT-AV1_patches -type f -name '*.patch' -print0 | sort -z | xargs -t -0 -n 1 patch -p1 -i &&     cd Build/linux &&     mkdir -p ../../Bin/Release &&     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DCMAKE_ASM_NASM_COMPILER=yasm ../.. &&     make -j8 &&     make install DESTDIR=/home/build &&     make install' returned a non-zero code: 123
Xeon/ubuntu-18.04/media/ffmpeg/CMakeFiles/build_xeon_ffmpeg_ubuntu1804.dir/build.make:57: recipe for target 'Xeon/ubuntu-18.04/media/ffmpeg/CMakeFiles/build_xeon_ffmpeg_ubuntu1804' failed
make[2]: *** [Xeon/ubuntu-18.04/media/ffmpeg/CMakeFiles/build_xeon_ffmpeg_ubuntu1804] Error 123
CMakeFiles/Makefile2:7482: recipe for target 'Xeon/ubuntu-18.04/media/ffmpeg/CMakeFiles/build_xeon_ffmpeg_ubuntu1804.dir/all' failed
make[1]: *** [Xeon/ubuntu-18.04/media/ffmpeg/CMakeFiles/build_xeon_ffmpeg_ubuntu1804.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jhou5** [comment]
The issue was found when upgrading AV1 to 0.8.2. Here is PR with the failure: https://github.com/OpenVisualCloud/Dockerfiles/pull/462

**Comment by TangZhiZhen** [comment]
https://github.com/OpenVisualCloud/Dockerfiles/pull/469

**Comment by jhou5** [comment]
SVT AV1 v0.8.2 failed to integration. Final one: #473
