### ISSUE TITLE
svt gst hevc plugin is upstreamed, should stop using the version in svt repo.

### ISSUE THREAD

**Issue by tianjunwork** [OpenVisualCloud/Dockerfiles#471]
https://01.org/blogs/tianjun/2020/svt-hevc-plugin-has-been-included-gstreamer-master

**Comment by 1480c1** [comment]
Does not seem like it's available in a release yet

**Comment by xwu2git** [comment]
We can only build from a released version. Master can change overtime and break things.
So we will adopt in the next gst release cycle.

**Comment by tianjunwork** [comment]
Thank you @xwu2git Xintian @1480c1 Chris for confirming.

**Comment by tianjunwork** [comment]
https://gstreamer.freedesktop.org/releases/1.18/
SVT-HEVC is included in gst 1.18 release. Thanks @1480c1 letting me know.

**Comment by l1yulong** [comment]
gst official release version 1.20.3 is already used in v23.06
