### ISSUE TITLE
ffmpeg & gst versions

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Dockerfiles#476]
Use n422 & v1.16.2 for latest fixes.

**Comment by jhou5** [comment]
@linxie47 is latest FFMPEG VA plugin workable for FFMPEG n422?

**Comment by linxie47** [comment]
@jhou5 We have to do some estimations @djie1

**Comment by linxie47** [comment]
Have tried n4.2.2 and didn't see any impact on analytics plugins.

**Comment by jhou5** [comment]
Good to know! Thanks @linxie47

**Comment by jhou5** [comment]
#530 #527
