### ISSUE TITLE
UNICODE exception

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Dockerfiles#501]
docker run --rm -it openvisualcloud/xeon-ubuntu1804-analytics-gst /bin/bash
root@0bb08ea66552:/home# python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x="\u8080"
>>> try:
...     raise Exception(x)
... except Exception as e:
...     print("Exception: "+str(e))
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
Exception: \u8080

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character '\u8080' in position 11: ordinal not in range(128)

However, if I do it on regular Ubuntu1804 on the host:
$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x="\u8080"
>>> try:
...     raise Exception(x)
... except Exception as e:
...     print("Exception "+str(e))
...
Exception 肀

**Comment by xwu2git** [comment]
I figured out. 
To use python with UNICODE, you need to add the following to the dockerfile:
ENV  PYTHONIOENCODING=UTF-8

**Comment by dpatel257** [comment]
Cool. working on a PR. Can you mention what test were you running so that I can confirm the deployed image?

**Comment by dpatel257** [comment]
So looks like python does have utf-8 bydefault. But if the OS(docker container in this case) has a different encoding it will consume it.
Both ubuntu/centos docker images have ANSI for some reason. That is why this happens.

Same reason, setting this PYTHONIOENCODING works
