### ISSUE TITLE
svt_hevc transcoded file not playable in browsers.

### ISSUE THREAD

**Issue by xwu2git** [OpenVisualCloud/Dockerfiles#504]
The original mp4 file is playable. After transcoding, the resulting mp4 file not playable in any browsers.

docker run --rm -v $(pwd):/mnt:rw -it openvisualcloud/xeon-ubuntu1804-media-ffmpeg:20.4 /bin/bash
root@aaa2e9ec0ae1:/home# ffmpeg -i /mnt/SmartStadiumV5.mp4 -c:v libsvt_hevc -preset 9 -c:a aac -f mp4 /mnt/SmartStadiumV5-svt.mp4
ffmpeg version 4.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr/local --extra-cflags= --extra-ldflags= --libdir=/usr/local/lib/x86_64-linux-gnu --extra-libs='-lpthread -lm' --enable-shared --enable-gpl --enable-libass --enable-libfreetype --disable-xlib --disable-sdl2 --enable-openssl --enable-nonfree --disable-vaapi --disable-hwaccels --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libsvthevc --enable-libsvtav1 --enable-libsvtvp9
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/mnt/SmartStadiumV5.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2020-04-28T23:06:29.000000Z
    title           : Smart Stadium
  Duration: 00:01:46.00, start: 0.000000, bitrate: 2265 kb/s
    Stream #0:0(eng): Video: h264 (Baseline) (avc1 / 0x31637661), yuv420p(tv), 1920x1080 [SAR 1:1 DAR 16:9], 2137 kb/s, 30 fps, 30 tbr, 30k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2020-04-28T23:06:30.000000Z
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
    Metadata:
      creation_time   : 2020-04-28T23:06:30.000000Z
      handler_name    : Mainconcept MP4 Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (libsvt_hevc))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
SVT [version]:  SVT-HEVC Encoder Lib v1.4.3
SVT [build]  :  GCC 7.5.0        64 bit
LIB Build date: May  8 2020 22:46:40
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 62
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode / Tune                                                        : 9 / 1
SVT [config]: EncoderBitDepth / CompressedTenBitFormat / EncoderColorFormat             : 8 / 0 / 1
SVT [config]: SourceWidth / SourceHeight / InterlacedVideo                              : 1920 / 1080 / 0
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType             : 30 / 1 / 32 / -1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure                  : 3 / 0 / 2
SVT [config]: BRC Mode / QP / LookaheadDistance / SceneChange                           : CQP / 32 / 17 / 1
SVT [config]: BitRateReduction / ImproveSharpness                                       : 0 / 0
SVT [config]: tileColumnCount / tileRowCount / tileSliceMode / Constraint MV            : 1 / 1 / 0 / 0
SVT [config]: De-blocking Filter / SAO Filter                                           : 1 / 1
SVT [config]: HME / UseDefaultHME                                                       : 1 / 1
SVT [config]: MV Search Area Width / Height                                             : 16 / 7
SVT [config]: HRD / VBV MaxRate / BufSize / BufInit                                     : 0 / 0 / 0 / 90
-------------------------------------------

SVT [WARNING] Elevated privileges required to run with real-time policies! Check Linux Best Known Configuration in User Guide to run application in real-time without elevated privileges!

Output #0, mp4, to '/mnt/SmartStadiumV5-svt.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    title           : Smart Stadium
    encoder         : Lavf58.29.100
    Stream #0:0(eng): Video: hevc (libsvt_hevc) (hev1 / 0x31766568), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=10-48, 7000 kb/s, 30 fps, 15360 tbn, 30 tbc (default)
    Metadata:
      creation_time   : 2020-04-28T23:06:30.000000Z
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : Lavc58.54.100 libsvt_hevc
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2020-04-28T23:06:30.000000Z
      handler_name    : Mainconcept MP4 Sound Media Handler
      encoder         : Lavc58.54.100 aac
frame=   28 fps=0.0 q=0.0 size=       0kB time=00:00:00.97 bitrate=   0.4kbits/s speed=1.94x  frame=   64 fps= 64 q=-0.0 size=       0kB time=00:00:02.29 bitrate=   0.2kbits/s speed=2.29x frame=   97 fps= 63 q=-0.0 size=       0kB time=00:00:03.29 bitrate=   0.1kbits/s speed=2.14x frame=  122 fps= 60 q=-0.0 size=       0kB time=00:00:03.99 bitrate=   0.1kbits/s speed=1.95x frame=  152 fps= 59 q=-0.0 size=       0kB time=00:00:04.96 bitrate=   0.1kbits/s speed=1.92x frame=  187 fps= 61 q=-0.0 size=       0kB time=00:00:06.29 bitrate=   0.1kbits/s speed=2.04x frame=  228 fps= 63 q=-0.0 size=       0kB time=00:00:07.63 bitrate=   0.0kbits/s speed=2.11x frame=  265 fps= 64 q=-0.0 size=       0kB time=00:00:08.96 bitrate=   0.0kbits/s speed=2.17x frame=  302 fps= 65 q=-0.0 size=     256kB time=00:00:10.28 bitrate= 203.9kbits/s speed=2.22x frame=  341 fps= 66 q=-0.0 size=     256kB time=00:00:11.30 bitrate= 185.5kbits/s speed= 2.2x frame=  382 fps= 67 q=-0.0 size=     256kB time=00:00:12.63 bitrate= 166.1kbits/s speed=2.23x frame=  420 fps= 68 q=-0.0 size=     256kB time=00:00:13.95 bitrate= 150.3kbits/s speed=2.26x frame=  460 fps= 68 q=-0.0 size=     512kB time=00:00:15.30 bitrate= 274.1kbits/s speed=2.27x frame=  495 fps= 68 q=-0.0 size=     512kB time=00:00:16.62 bitrate= 252.3kbits/s speed=2.29x frame=  535 fps= 69 q=-0.0 size=     512kB time=00:00:17.97 bitrate= 233.4kbits/s speed=2.32x frame=  572 fps= 69 q=-0.0 size=     768kB time=00:00:18.99 bitrate= 331.3kbits/s speed= 2.3x frame=  612 fps= 70 q=-0.0 size=     768kB time=00:00:20.31 bitrate= 309.7kbits/s speed=2.31x frame=  647 fps= 70 q=-0.0 size=     768kB time=00:00:21.64 bitrate= 290.7kbits/s speed=2.33x frame=  686 fps= 70 q=-0.0 size=    1024kB time=00:00:22.96 bitrate= 365.3kbits/s speed=2.34x frame=  726 fps= 70 q=-0.0 size=    1024kB time=00:00:24.28 bitrate= 345.4kbits/s speed=2.35x frame=  762 fps= 70 q=-0.0 size=    1280kB time=00:00:25.30 bitrate= 414.3kbits/s speed=2.33x frame=  792 fps= 70 q=-0.0 size=    1280kB time=00:00:26.56 bitrate= 394.8kbits/s speed=2.34x frame=  826 fps= 70 q=-0.0 size=    1280kB time=00:00:27.63 bitrate= 379.5kbits/s speed=2.33x frame=  854 fps= 69 q=-0.0 size=    1536kB time=00:00:28.63 bitrate= 439.5kbits/s speed=2.31x frame=  888 fps= 69 q=-0.0 size=    1536kB time=00:00:29.62 bitrate= 424.7kbits/s speed= 2.3x frame=  914 fps= 68 q=-0.0 size=    1536kB time=00:00:30.62 bitrate= 410.9kbits/s speed=2.29x frame=  936 fps= 67 q=-0.0 size=    1536kB time=00:00:31.30 bitrate= 402.0kbits/s speed=2.25x frame=  965 fps= 67 q=-0.0 size=    1792kB time=00:00:32.29 bitrate= 454.5kbits/s speed=2.24x frame=  996 fps= 67 q=-0.0 size=    1792kB time=00:00:33.29 bitrate= 440.9kbits/s speed=2.23x frame= 1022 fps= 66 q=-0.0 size=    2048kB time=00:00:33.99 bitrate= 493.5kbits/s speed= 2.2x frame= 1059 fps= 66 q=-0.0 size=    2048kB time=00:00:35.29 bitrate= 475.4kbits/s speed=2.21x frame= 1087 fps= 66 q=-0.0 size=    2048kB time=00:00:36.29 bitrate= 462.3kbits/s speed= 2.2x frame= 1122 fps= 66 q=-0.0 size=    2304kB time=00:00:37.47 bitrate= 503.6kbits/s speed=2.21x frame= 1157 fps= 66 q=-0.0 size=    2304kB time=00:00:38.63 bitrate= 488.5kbits/s speed=2.21x frame= 1191 fps= 66 q=-0.0 size=    2304kB time=00:00:39.63 bitrate= 476.2kbits/s speed= 2.2x frame= 1222 fps= 66 q=-0.0 size=    2560kB time=00:00:40.65 bitrate= 515.8kbits/s speed=2.19x frame= 1255 fps= 66 q=-0.0 size=    2560kB time=00:00:41.95 bitrate= 499.8kbits/s speed=2.21x frame= 1285 fps= 66 q=-0.0 size=    2560kB time=00:00:42.95 bitrate= 488.2kbits/s speed= 2.2x frame= 1316 fps= 65 q=-0.0 size=    2560kB time=00:00:43.95 bitrate= 477.1kbits/s speed=2.18x frame= 1351 fps= 65 q=-0.0 size=    2816kB time=00:00:44.95 bitrate= 513.2kbits/s speed=2.18x frame= 1388 fps= 66 q=-0.0 size=    2816kB time=00:00:46.30 bitrate= 498.2kbits/s speed=2.19x frame= 1426 fps= 66 q=-0.0 size=    3072kB time=00:00:47.62 bitrate= 528.4kbits/s speed= 2.2x frame= 1461 fps= 66 q=-0.0 size=    3072kB time=00:00:48.62 bitrate= 517.6kbits/s speed=2.19x frame= 1495 fps= 66 q=-0.0 size=    3072kB time=00:00:49.96 bitrate= 503.6kbits/s speed= 2.2x frame= 1531 fps= 66 q=-0.0 size=    3072kB time=00:00:50.96 bitrate= 493.8kbits/s speed= 2.2x frame= 1555 fps= 66 q=-0.0 size=    3328kB time=00:00:51.96 bitrate= 524.6kbits/s speed=2.19x frame= 1592 fps= 66 q=-0.0 size=    3328kB time=00:00:53.15 bitrate= 512.9kbits/s speed= 2.2x frame= 1626 fps= 66 q=-0.0 size=    3584kB time=00:00:54.28 bitrate= 540.8kbits/s speed= 2.2x frame= 1652 fps= 66 q=-0.0 size=    3584kB time=00:00:54.98 bitrate= 534.0kbits/s speed=2.18x frame= 1680 fps= 65 q=-0.0 size=    3584kB time=00:00:55.96 bitrate= 524.7kbits/s speed=2.17x frame= 1705 fps= 65 q=-0.0 size=    3584kB time=00:00:56.95 bitrate= 515.5kbits/s speed=2.17x frame= 1732 fps= 65 q=-0.0 size=    3584kB time=00:00:57.63 bitrate= 509.4kbits/s speed=2.15x frame= 1770 fps= 65 q=-0.0 size=    3840kB time=00:00:58.95 bitrate= 533.6kbits/s speed=2.16x frame= 1812 fps= 65 q=-0.0 size=    3840kB time=00:01:00.30 bitrate= 521.7kbits/s speed=2.16x frame= 1840 fps= 65 q=-0.0 size=    3840kB time=00:01:01.30 bitrate= 513.2kbits/s speed=2.16x frame= 1862 fps= 64 q=-0.0 size=    3840kB time=00:01:01.99 bitrate= 507.4kbits/s speed=2.14x frame= 1892 fps= 64 q=-0.0 size=    4096kB time=00:01:02.99 bitrate= 532.7kbits/s speed=2.14x frame= 1920 fps= 64 q=-0.0 size=    4352kB time=00:01:03.97 bitrate= 557.3kbits/s speed=2.14x frame= 1945 fps= 64 q=-0.0 size=    4352kB time=00:01:04.96 bitrate= 548.7kbits/s speed=2.13x frame= 1974 fps= 64 q=-0.0 size=    4608kB time=00:01:05.96 bitrate= 572.2kbits/s speed=2.13x frame= 2004 fps= 64 q=-0.0 size=    4864kB time=00:01:06.96 bitrate= 595.0kbits/s speed=2.13x frame= 2029 fps= 63 q=-0.0 size=    4864kB time=00:01:07.63 bitrate= 589.1kbits/s speed=2.11x frame= 2055 fps= 63 q=-0.0 size=    5120kB time=00:01:08.63 bitrate= 611.1kbits/s speed=2.11x frame= 2087 fps= 63 q=-0.0 size=    5120kB time=00:01:09.63 bitrate= 602.3kbits/s speed=2.11x frame= 2118 fps= 63 q=-0.0 size=    5376kB time=00:01:10.63 bitrate= 623.5kbits/s speed= 2.1x frame= 2147 fps= 63 q=-0.0 size=    5376kB time=00:01:11.63 bitrate= 614.8kbits/s speed= 2.1x frame= 2178 fps= 63 q=-0.0 size=    5376kB time=00:01:12.63 bitrate= 606.4kbits/s speed= 2.1x frame= 2198 fps= 63 q=-0.0 size=    5632kB time=00:01:13.30 bitrate= 629.4kbits/s speed=2.09x frame= 2225 fps= 62 q=-0.0 size=    5632kB time=00:01:14.30 bitrate= 620.9kbits/s speed=2.09x frame= 2254 fps= 62 q=-0.0 size=    5888kB time=00:01:15.30 bitrate= 640.5kbits/s speed=2.08x frame= 2281 fps= 62 q=-0.0 size=    5888kB time=00:01:15.97 bitrate= 634.9kbits/s speed=2.07x frame= 2301 fps= 62 q=-0.0 size=    5888kB time=00:01:16.62 bitrate= 629.5kbits/s speed=2.06x frame= 2321 fps= 62 q=-0.0 size=    6144kB time=00:01:17.29 bitrate= 651.1kbits/s speed=2.05x frame= 2346 fps= 61 q=-0.0 size=    6144kB time=00:01:18.29 bitrate= 642.8kbits/s speed=2.05x frame= 2365 fps= 61 q=-0.0 size=    6144kB time=00:01:18.97 bitrate= 637.3kbits/s speed=2.04x frame= 2388 fps= 61 q=-0.0 size=    6400kB time=00:01:19.62 bitrate= 658.5kbits/s speed=2.03x frame= 2412 fps= 61 q=-0.0 size=    6400kB time=00:01:20.29 bitrate= 653.0kbits/s speed=2.02x frame= 2434 fps= 60 q=-0.0 size=    6400kB time=00:01:21.29 bitrate= 644.9kbits/s speed=2.02x frame= 2455 fps= 60 q=-0.0 size=    6656kB time=00:01:21.96 bitrate= 665.2kbits/s speed=2.01x frame= 2480 fps= 60 q=-0.0 size=    6656kB time=00:01:22.63 bitrate= 659.8kbits/s speed=   2x frame= 2506 fps= 60 q=-0.0 size=    6912kB time=00:01:23.63 bitrate= 677.0kbits/s speed=   2x frame= 2532 fps= 60 q=-0.0 size=    6912kB time=00:01:24.61 bitrate= 669.2kbits/s speed=   2x frame= 2561 fps= 60 q=-0.0 size=    6912kB time=00:01:25.28 bitrate= 663.9kbits/s speed=1.99x frame= 2596 fps= 60 q=-0.0 size=    7168kB time=00:01:26.63 bitrate= 677.8kbits/s speed=   2x frame= 2626 fps= 60 q=-0.0 size=    7168kB time=00:01:27.63 bitrate= 670.1kbits/s speed=   2x frame= 2654 fps= 60 q=-0.0 size=    7424kB time=00:01:28.63 bitrate= 686.2kbits/s speed=   2x frame= 2687 fps= 60 q=-0.0 size=    7424kB time=00:01:29.62 bitrate= 678.5kbits/s speed=   2x frame= 2719 fps= 60 q=-0.0 size=    7680kB time=00:01:30.62 bitrate= 694.2kbits/s speed=   2x frame= 2759 fps= 60 q=-0.0 size=    7680kB time=00:01:31.97 bitrate= 684.0kbits/s speed=2.01x frame= 2797 fps= 60 q=-0.0 size=    7680kB time=00:01:33.29 bitrate= 674.3kbits/s speed=2.01x frame= 2837 fps= 61 q=-0.0 size=    7680kB time=00:01:34.62 bitrate= 664.9kbits/s speed=2.02x frame= 2878 fps= 61 q=-0.0 size=    7936kB time=00:01:35.96 bitrate= 677.4kbits/s speed=2.03x frame= 2914 fps= 61 q=-0.0 size=    7936kB time=00:01:37.29 bitrate= 668.2kbits/s speed=2.03x frame= 2957 fps= 61 q=-0.0 size=    7936kB time=00:01:38.63 bitrate= 659.1kbits/s speed=2.04x frame= 2991 fps= 61 q=-0.0 size=    7936kB time=00:01:39.63 bitrate= 652.5kbits/s speed=2.04x frame= 3022 fps= 61 q=-0.0 size=    7936kB time=00:01:40.65 bitrate= 645.9kbits/s speed=2.04x frame= 3058 fps= 61 q=-0.0 size=    8192kB time=00:01:41.95 bitrate= 658.2kbits/s speed=2.04x frame= 3086 fps= 61 q=-0.0 size=    8192kB time=00:01:42.95 bitrate= 651.8kbits/s speed=2.04x frame= 3120 fps= 61 q=-0.0 size=    8192kB time=00:01:43.95 bitrate= 645.6kbits/s speed=2.04x frame= 3150 fps= 61 q=-0.0 size=    8192kB time=00:01:44.95 bitrate= 639.4kbits/s speed=2.04x frame= 3179 fps= 61 q=-0.0 Lsize=    8552kB time=00:01:45.99 bitrate= 660.9kbits/s speed=2.03x
video:6763kB audio:1672kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.388115%
[aac @ 0x563ae2fdd300] Qavg: 284.942
root@aaa2e9ec0ae1:/home# exit

**Comment by tianjunwork** [comment]
I tried with ffmpeg+SVT-HEVC plugin on bare metal, `ffmpeg -i my.mp4 -c:v libsvt_hevc -preset 9 -c:a aac -f mp4 test.mp4` results a playable mp4 file.
@xwu2git does your browser support hevc decoding? the original file is avc `Stream #0:0(eng): Video: h264 (Baseline)`.

**Comment by xwu2git** [comment]
yes, with libx264 -preset veryfast, the resulted file is playable. Can you try with the docker image?

**Comment by tianjunwork** [comment]
with libx264, the result file is AVC not HEVC.
As far as I know, browsers yet support HEVC decode now.

**Comment by xwu2git** [comment]
My mistake. This point slips me.
