### ISSUE TITLE
detection and ffplay issues in  openvisualcloud/vcaca-ubuntu1804-analytics-dev:latest

### ISSUE THREAD

**Issue by sramakintel** [OpenVisualCloud/Dockerfiles#516]
docker run command:
 docker run -it --privileged --rm --user root -v /var/tmp:/var/tmp --device=/dev/dri --device=/dev/ion:/dev/ion  -v /root/<path to model and video>/:/home/<path to model and video>  openvisualcloud/vcaca-ubuntu1804-analytics-dev:latest
Issue 1:
command 
ffmpeg -profiling_all -flags unaligned -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128 -i /home/videos/one-by-one-person-detection.mp4 -vf detect=model=/home/models/person-detection-retail-0013/FP16/person-detection-retail-0013.xml:device=HDDL -f null /dev/null

error:

  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41
    creation_time   : 2017-09-26T16:57:49.000000Z
  Duration: 00:02:19.40, start: 0.000000, bitrate: 188 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m), 768x432, 187 kb/s, 10 fps, 10 tbr, 200k tbn, 20 tbc (default)
    Metadata:
      creation_time   : 2017-09-26T16:57:49.000000Z
      handler_name    : ?Mainconcept Video Media Handler
      encoder         : AVC Coding
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> wrapped_avframe (native))
Press [q] to stop, [?] for help
[AVFilterGraph @ 0x55d03f546580] No such filter: 'detect'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0

Issue 2:
Issue with vaapi and hwaccel

command:
 ffplay -flags unaligned -hwaccel vaapi -hwaccel_output_format vaapi -hwaccel_device /dev/dri/renderD128 -i /home/videos/one-by-one-person-detection.mp4 -vf detect=model=/home/models/person-detection-retail-0013/FP16/person-detection-retail-0013.xml:device=HDDL,ocv_overlay

error:

Failed to set value 'vaapi' for option 'hwaccel': Option not found

**Comment by jhou5** [comment]
@dpatel257 can you pls. help check this?

**Comment by l1yulong** [comment]
No longer support VCACA platform
