### ISSUE TITLE
incorrect way of adding a library path only to python3

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#546]
Failed to compile the VideoDuration sample against xeon-ubuntu1804-analytics-dev:20.7:

_Step 5/19 : RUN cd /opt && git clone https://github.com/IntelLabs/vdms && cd vdms && git checkout tags/v2.0.1 && mkdir db && scons -j$(nproc) INTEL_PATH=/opt --no-server
---> Running in 45603b764ea8
Cloning into 'vdms'...
Note: checking out 'tags/v2.0.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>
HEAD is now at cb271f7 Patch for Video Curation Tempfix to enable FindVideo results to return to client, previous bug when blob is disabled, user required results are masked out Increase vdms message size limit to 1GB
Traceback (most recent call last):
  File "/usr/bin/scons", line 99, in <module>
    import pkg_resources
  File "/mo_libs/pkg_resources/__init__.py", line 1380
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
The command '/bin/sh -c cd /opt && git clone https://github.com/IntelLabs/vdms && cd vdms && git checkout tags/v2.0.1 && mkdir db && scons -j$(nproc) INTEL_PATH=/opt --no-server' returned a non-zero code: 1
ingest/CMakeFiles/build_lcc_ingest.dir/build.make:57: recipe for target 'ingest/CMakeFiles/build_lcc_ingest' failed
make[2]: *** [ingest/CMakeFiles/build_lcc_ingest] Error 1_

Made it working by removing PYTHONPATH.
Video Curation sample used scons as the make replacement. Scons is python2 only. Adding python3 libraries into PYTHONPATH confuses scons.
 
See https://stackoverflow.com/questions/34066261/how-to-set-different-pythonpath-variables-for-python3-and-python2-respectively for proper ways of adding a library path only to python3.

**Comment by l1yulong** [comment]
Passed with Ubuntu 20.04/22.04. Ubuntu 18.04 is EOL.
