### ISSUE TITLE
openvino build failed from scratch in some platforms/OS - No module named 'skbuild'

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#549]
The issue was found when building some CentOS 7x analytics dev images with no previous docker cache.

Build Log：
Step 148/194 : RUN cd openvino/tools &&     python3 -m pip install -r benchmark/requirements.txt
 ---> Running in c4881aa00685
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting py-cpuinfo (from -r benchmark/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f6/f5/8e6e85ce2e9f6e05040cf0d4e26f43a4718bcc4bce988b433276d4b1a5c1/py-cpuinfo-7.0.0.tar.gz (95kB)
Requirement already satisfied: numpy in /usr/local/lib64/python3.6/site-packages (from -r benchmark/requirements.txt (line 2))
Collecting progress (from -r benchmark/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/38/ef/2e887b3d2b248916fc2121889ce68af8a16aaddbe82f9ae6533c24ff0d2b/progress-1.5.tar.gz
Collecting opencv-python (from -r benchmark/requirements.txt (line 4))
  

Downloading https://files.pythonhosted.org/packages/a1/d6/8422797e35f8814b1d9842530566a949d9b5850a466321a6c1d5a99055ee/opencv-python-4.3.0.38.tar.gz (88.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-drgaf_sg/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-drgaf_sg/opencv-python/
The command '/bin/sh -c cd openvino/tools &&     python3 -m pip install -r benchmark/requirements.txt' returned a non-zero code: 1

**Comment by koles289** [comment]
Hi, I have exactly  the same problem after downloading OpenVino toolkit for linux with FPGA support version 2020.4.287. 
May I ask, if I download the most recent version, the error will be solved?

**Comment by Grandmother** [comment]
Hi, this problem is described in [issue in official opencv-python repo](https://github.com/skvark/opencv-python/issues/372) and in [their FAQ](https://github.com/skvark/opencv-python#frequently-asked-questions).

**Comment by jhou5** [comment]
add below package would fix this issue: pip3 install scikit-build, you can refer to PR #550 . The fix is already in master and v20.7 branch.
