### ISSUE TITLE
weavenet installation error from setup_weave.sh

### ISSUE THREAD

**Issue by jainricha** [OpenVisualCloud/Dockerfiles#567]
Hi,

I am trying to install weavenet on a VM which I want to attach as a worker node to my master node.

Below are the steps I did:
1. Installed Docker
2, Installed Kubernetes
3. Install WeaveNet on Master node.
4. Did Kubeadm init on master node

Before running Kubeadm join, I am installing WeaveNet on my worker VM using the below steps:
1. Installed Docker
2. Installed Kubernetes
3. Install weavenet. Here I am getting below installation error:

`[root@host-172-19-104-119 script]# ./setup_weave.sh rsu203
Create /etc/weave.conf
PEERS="masternode"
IP_RANGE="172.30.0.0/16"
Download the WeaveNet software
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
0 0 0 0 0 0 0 0 --:--:-- 0:00:02 --:--:-- 0
100 629 100 629 0 0 224 0 0:00:02 0:00:02 --:--:-- 224
100 51395 100 51395 0 0 10774 0 0:00:04 0:00:04 --:--:-- 37215
Setup weave.service
[Unit]
Description=Weave Network
Documentation=http://docs.weave.works/weave/latest_release/
Requires=docker.service
After=docker.service
Before=kubelet.service

[Service]
EnvironmentFile=/etc/weave.conf
Environment="CHECKPOINT_DISABLE=1"
ExecStartPre=/usr/local/bin/weave reset --force
ExecStartPre=/usr/local/bin/weave launch --no-restart --name fa:16:3e:5f:0d:79 --ipalloc-range=${IP_RANGE} $PEERS
ExecStartPre=/bin/sh -c 'echo KUBELET_EXTRA_ARGS=\"--node-ip=$$(/usr/local/bin/weave expose)\" > /etc/default/kubelet'
ExecStart=/usr/bin/docker attach weave
ExecStop=/usr/local/bin/weave stop

[Install]
WantedBy=multi-user.target
Enable weave.service
Start weave.service
**Job for weave.service failed because the control process exited with error code. See "systemctl status weave.service" and "journalctl -xe" for details.**`

Output of journalctl -xe:
`
Sep 28 11:18:26 host-172-19-104-119 NetworkManager[1100]: <info>  [1601306306.5262] device (weave): state change: ip-config -> ip-check (reason 'none
Sep 28 11:18:26 host-172-19-104-119 NetworkManager[1100]: <info>  [1601306306.5267] device (vxlan-6784): state change: unmanaged -> unavailable (reas
Sep 28 11:18:26 host-172-19-104-119 NetworkManager[1100]: <info>  [1601306306.5274] device (vxlan-6784): enslaved to non-master-type device datapath;
Sep 28 11:18:26 host-172-19-104-119 NetworkManager[1100]: <info>  [1601306306.5275] device (weave): state change: ip-check -> secondaries (reason 'no
Sep 28 11:18:26 host-172-19-104-119 NetworkManager[1100]: <info>  [1601306306.5277] device (weave): state change: secondaries -> activated (reason 'n
Sep 28 11:18:26 host-172-19-104-119 NetworkManager[1100]: <info>  [1601306306.5313] device (weave): Activation: successful, device activated.
Sep 28 11:18:26 host-172-19-104-119 NetworkManager[1100]: <info>  [1601306306.5318] device (vxlan-6784): state change: unavailable -> disconnected (r
Sep 28 11:18:26 host-172-19-104-119 nm-dispatcher[4971]: req:2 'up' [weave]: new request (3 scripts)
Sep 28 11:18:26 host-172-19-104-119 nm-dispatcher[4971]: req:2 'up' [weave]: start running ordered scripts...
Sep 28 11:18:26 host-172-19-104-119 dockerd[1395]: time="2020-09-28T11:18:26-04:00" level=info msg="shim reaped" id=54fb30135556c861d73bef2f8ff0a4b0d
Sep 28 11:18:26 host-172-19-104-119 dockerd[1395]: time="2020-09-28T11:18:26.690733486-04:00" level=info msg="ignoring event" module=libcontainerd na
Sep 28 11:18:26 host-172-19-104-119 weave[5087]: The weave container has died. Consult the container logs for further details.
Sep 28 11:18:26 host-172-19-104-119 dockerd[1395]: time="2020-09-28T11:18:26-04:00" level=info msg="shim reaped" id=ddc1677f357fe51de77cc7c885bd713a5
Sep 28 11:18:26 host-172-19-104-119 dockerd[1395]: time="2020-09-28T11:18:26.885422562-04:00" level=info msg="ignoring event" module=libcontainerd na
Sep 28 11:18:26 host-172-19-104-119 systemd[1]: weave.service: control process exited, code=exited status=1
Sep 28 11:18:26 host-172-19-104-119 systemd[1]: Failed to start Weave Network.
`
Any idea what is it that causes this issue?

**Comment by xwu2git** [comment]
Check the logs in the weavenet container: docker logs -f <wavenet container>. See if there is anything wrong.

**Comment by jainricha** [comment]
> Check the logs in the weavenet container: docker logs -f . See if there is anything wrong.

Here are the weave container logs:

`root@vcac-node:~# docker logs -f 363fdcac6036
INFO: 2020/09/30 13:12:45.623058 Command line options: map[H:[unix:///var/run/weave/weave.sock] datapath:datapath dns-listen-address:172.17.0.1:53 docker-bridge:docker0 host-root:/host http-addr:127.0.0.1:6784 ipalloc-range:10.244.0.0/16 name:00:e0:ec:40:d1:29 nickname:vcac-node plugin:true port:6783 proxy:true resolv-conf:/var/run/weave/etc/stub-resolv.conf status-addr:127.0.0.1:6782 weave-bridge:weave]
INFO: 2020/09/30 13:12:45.623304 weave  2.7.0
INFO: 2020/09/30 13:12:45.624853 Docker API on unix:///var/run/docker.sock: &[BuildTime=2018-07-18T19:07:56.000000000+00:00 Platform={"Name":""} Components=[{"Details":{"ApiVersion":"1.38","Arch":"amd64","BuildTime":"2018-07-18T19:07:56.000000000+00:00","Experimental":"false","GitCommit":"0ffa825","GoVersion":"go1.10.3","KernelVersion":"5.3.18-1.b4f0e4e.vca+","MinAPIVersion":"1.12","Os":"linux"},"Name":"Engine","Version":"18.06.0-ce"}] Version=18.06.0-ce MinAPIVersion=1.12 Arch=amd64 KernelVersion=5.3.18-1.b4f0e4e.vca+ ApiVersion=1.38 GitCommit=0ffa825 GoVersion=go1.10.3 Os=linux]
INFO: 2020/09/30 13:12:45.629918 proxy listening on unix:///var/run/weave/weave.sock
INFO: 2020/09/30 13:12:45.635257 failed to create weave-test-commentd171e73e; disabling comment support
WARN: 2020/09/30 13:12:45.640903 Skipping bridge creation of "bridged_fastdp" due to: : bridge not supported
FATA: 2020/09/30 13:12:45.642680 creating dummy interface: operation not supported`

**Comment by xwu2git** [comment]
Forwarded your comments to the VCAC-A dev team. 
As a workaround, do you have to install weavenet? If you have a 1-node setup that Kubernetes master is on your VCAC-A host, you can skip the WeaveNet setup. Alternatively, you can probably use the VCAC-A bridge network mode. This does not require to use WeaveNet either.

**Comment by jainricha** [comment]
> Forwarded your comments to the VCAC-A dev team.
> As a workaround, do you have to install weavenet? If you have a 1-node setup that Kubernetes master is on your VCAC-A host, you can skip the WeaveNet setup. Alternatively, you can probably use the VCAC-A bridge network mode. This does not require to use WeaveNet either.

If I skip the weavenet setup, the vcac worker node is always in NotReady State and I am not sure if I will be able to schedule pods on the same. What is VCAC-A bridge network mode? Can you give more details? Will it allow me to use VCAC as worker node in my cluster.

Btw, just to share more findings, I skipped weavenet installation on vcac node and did the weavenet installation using weave-net yaml via kubectl apply -f weave-net.yaml command, Now this shows two weave pods running on my cluster, but the one which is running on VCAC worker node is in State "CrashLoopBackOff".

Checking the  container logs at VCAC in /var/log/contatiner/<weave specific log> the error I could see it 
"Failed to retrieve list of ipsets"

**Comment by yiliu120** [comment]
Not sure if you can use flannel as alternative  solution.

Example:
$ wget https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml
$ sed -i “s/50Mi/100Mi/g” kube-flannel.yml
$ kubectl apply -f     kube-flannel.yml
$ kubectl taint nodes --all node-role.kubernetes.io/master-  (if K8S master is in the VCAC-A host)
