### ISSUE TITLE
Rebuild time improvement

### ISSUE THREAD

**Issue by umed** [OpenVisualCloud/Dockerfiles#65]
I think we can put each component into its own stage.
When one component has dependencies on other components we can install those components like in the final image.
It makes us available to reuse stages that were not changed.

For example:

 * **dldt** has dependencies only on CMake and OpenCV hence we install into dldt's stage CMake and OpenCV
 * **gstreamer** has dependencies on CMake and OpenCV - we install into dldt's stage CMake and OpenCV

When we need to update **dldt** we do not need to rebuild **gstreamer**, 'cause **gstreamer** doesn't depend on **dldt**.

**Comment by umed** [comment]
@jhou5 what do you think about it?

**Comment by jhou5** [comment]
Thanks for the suggestion. Can you specific details on how to if you have idea?
We are using Travis-CI cloud service which would setup clean VMs, thus build have to from scratch every time thus hard to reuse stages from previous build. We are investigating Travis-CI cache functions but it looks not good support to docker, thus we moving to see if can register physical server which can reuse previous build stages.

Welcome to any good idea to improve the build time.

**Comment by umed** [comment]
Will try to make an example

**Comment by jhou5** [comment]
It would be greatly helpful. Thanks!

**Comment by jhou5** [comment]
Already enabling dockerhub build cache, no rebuild time now if no code change for a component or its upstreamed components.
