### ISSUE TITLE
xeone3-ubuntu1804-analytics-gst:20.10 image does not detect Comet Lake GPU

### ISSUE THREAD

**Issue by whbruce** [OpenVisualCloud/Dockerfiles#662]
Steps to reproduce:

On A Kaby Lake system
```
$ grep "model name" /proc/cpuinfo | head -1
model name      : Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
$ docker run -it --device /dev/dri  --entrypoint /bin/bash openvisualcloud/xeone3-ubuntu1804-analytics-gst:20.10 -c "clinfo -l"
Platform #0: Intel(R) OpenCL HD Graphics
  -- Device #0: Intel(R) Gen9 HD Graphics NEO
```

On a Comet Lake system (clinfo detects no devices)
```
$  grep "model name" /proc/cpuinfo | head -1
model name      : Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
$ docker run -it --device /dev/dri  --entrypoint /bin/bash openvisualcloud/xeone3-ubuntu1804-analytics-gst:20.10 -c "clinfo -l"
```

**Comment by dpatel257** [comment]
Hello @whbruce ,
We officially support Xeon platforms, as Comet Lake comes under client CPU, we do not formally test it. Have you tried running OpenCL on baremetal comet lake and checked if clinfo is working.

**Comment by whbruce** [comment]
@dpatel257 thanks for reply, even though it is over 8 months late :-)

The compute stack you used for for 20.10 did not support CML, so we moved to using OpenVINO container that did. But good point, your container was only intended for Xeon support, so I am closing this issue.
