### ISSUE TITLE
Ubuntu 20.04 owt image test failed

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#678]
1: ./video-f065a40ce759580a640b@10.165.31.58_122.log:2021-03-03 22:19:25.897  - ERROR: VideoNode - Error: /home/owt/video_agent/videoMixer_sw/build/Release/videoMixer-sw.node: undefined symbol: _ZTVN7cricket10VideoCodecE
1: ./video-f065a40ce759580a640b@10.165.31.58_37.log:2021-03-03 22:19:19.157  - ERROR: VideoNode - Error: /home/owt/video_agent/videoMixer_sw/build/Release/videoMixer-sw.node: undefined symbol: _ZTVN7cricket10VideoCodecE
1: ./video-f065a40ce759580a640b@10.165.31.58_120.log:2021-03-03 22:19:25.727  - ERROR: VideoNode - Error: /home/owt/video_agent/videoMixer_sw/build/Release/videoMixer-sw.node: undefined symbol: _ZTVN7cricket10VideoCodecE
1: ./cluster-manager.stdout:2021-03-03 22:19:10.552  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: connect ECONNREFUSED 127.0.0.1:5672
1: ./cluster-manager.stdout:2021-03-03 22:19:11.557  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: connect ECONNREFUSED 127.0.0.1:5672
1: ./cluster-manager.stdout:2021-03-03 22:19:12.558  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: connect ECONNREFUSED 127.0.0.1:5672
1: ./cluster-manager.stdout:2021-03-03 22:19:13.561  - INFO: AmqpClient - Connection to rabbitMQ server error { Error: connect ECONNREFUSED 127.0.0.1:5672
1: ./video-f065a40ce759580a640b@10.165.31.58_62.log:2021-03-03 22:19:21.068  - ERROR: VideoNode - Error: /home/owt/video_agent/videoMixer_sw/build/Release/videoMixer-sw.node: undefined symbol: _ZTVN7cricket10VideoCodecE

**Comment by l1yulong** [comment]
Fixed in v23.06
