### ISSUE TITLE
[Security] Vulnerabilities present in release v21.3

### ISSUE THREAD

**Issue by dpatel257** [OpenVisualCloud/Dockerfiles#713]
These vulnerabilities were found as a part of SNYK scan and they are present in Release v21.3.
[ovc_dockerfiles_all_disposition.xlsx](https://github.com/OpenVisualCloud/Dockerfiles/files/6185559/ovc_dockerfiles_all_disposition.xlsx)

**Comment by l1yulong** [comment]
SNYK scan issues are clean in v23.06
