### ISSUE TITLE
How Webrtc-agent get media streams?

### ISSUE THREAD

**Issue by stepin105519** [OpenVisualCloud/Dockerfiles#789]
Hi all, 

For a month, I'm working on OWT. 
I'm confused with streaming-agent and webRTC-agent. 

Let say I have RTSP streaming, What is the role of the streaming agent?, is this the one that takes RTSP source URL.

Will the webRTC-agent receive the media from the streaming agent so it can transfer the streams to webRTC clients by creating a web socket?

**Comment by dpatel257** [comment]
Hi Qijujiao, Anything you can comment here?
@qwu16

**Comment by qwu16** [comment]
Hi, stepin. Streaming agent and webrtc agent both work as access agent in OWT. Streaming agent is used to pull external stream to OWT through RTSP/RTMP protocol and push OWT stream to external server through RTMP/HLS protocol. These external stream operations are done by OWT restful API: https://software.intel.com/sites/products/documentation/webrtc/restapi/. 

webrtc agent is used to publish/subscribe webrtc stream through javascript/android/ios/windows sdk. client and owt server signaling communication is processed through socketio, streaming between client and owt server is transported through webrtc protocol. 

In you scenario, RTSP stream will be added to OWT streaming agent through Restful API, then a new stream representing the rtsp stream will be generated, any client in the same room will be notified with "stream-added" event and then client can call subscribe API in client sdk (through socketio),  then the rtsp stream will be forwarded to webrtc agent in OWT and transferred to client.

**Comment by stepin105519** [comment]
Hi,

Thanks @qwu16.  I can see the conference.join and conference.subscribe calls in the client. Will the webRTC-agent be triggered only when the client subscribes to the stream? 
'RTSP stream will be added to OWT streaming agent through Restful API', is it happening through streaming-ins and avstreamin function call?
'the rtsp stream will be forwarded to webrtc agent in OWT and transferred to client'. will it be the direct RTSP stream or HLS/DASH based media packets? 
Will room have RTSP streams or HLS/DASH media packets?
Also, how do the agents communicate between each other?, Is it through RPC or AMQP and RabbitMQ? 
OWT says that it will be able to do video conference which streams out to many endpoints. Will there be a peer-to-peer connection from server to all the subscribed clients, how will the webRTC send the media to its clients?

**Comment by qwu16** [comment]
> Hi,
> 
> Thanks @qwu16. I can see the conference.join and conference.subscribe calls in the client. Will the webRTC-agent be triggered only when the client subscribes to the stream? Will room have RTSP streams or HLS/DASH media packets? **'RTSP stream will be added to OWT streaming agent through Restful API'**, is it happening through streaming-ins and avstreamin function call? **'the rtsp stream will be forwarded to webRTC-agent in OWT and transferred to client'**. will it be the direct RTSP stream or HLS/DASH based media packets? Also, how do the agents communicate between each other?, Is it through RPC or AMQP and RabbitMQ? OWT says that it will be able to do video conference which streams out to many endpoints. Will there be a peer-to-peer connection from server to all the subscribed clients, how will the webRTC send the media to its clients?

**Comment by qwu16** [comment]
Please see my comments:
1. When clients call publish/subscribe API to trigger WebRTC peer connection between OWT server and clients. 
2. For RTSP/RTMP, OWT streaming agent will work as a RTSP/RTMP client to pull/push media stream from/to remote RTSP/RTMP server
3. Restful API will trigger the streaming agent to work as RTSP/RTMP client to pull/push media stream from/to remote RTSP/RTMP server
4. OWT agents communicates with each other through RabbitMQ
5. For WebRTC, OWT server will establish peer connection with each client and they send media stream through this WebRTC peer connection
