### ISSUE TITLE
VCAC-A script uses privileged mode

### ISSUE THREAD

**Issue by dpatel257** [OpenVisualCloud/Dockerfiles#793]

**Comment by eero-t** [comment]
What in VCAC-A needs CAP_SYS_RAWIO?

**Comment by dpatel257** [comment]
This was created long ago, where we didn't want to use privileged mode to access 'devices' from container that are sitting on host. Hence the option. 
It's an option we never really explored. :)

**Comment by eero-t** [comment]
Are you saying that privileged mode is NOT actually used, i.e. this bug should be closed, or that you consider it acceptable to use privileged mode?

---

I do not think that any multi-user cloud system would allow pods with privileged mode, as it allows processes to escape the containment, and basically grants them full root access to the host (one definitely would not want to expose any such service to internet).

Especially when e.g. using GPU device does not need privileged mode, any capabilities, nor any specific user [1].  Pod just needs to ask k8s for GPU device resource (provided by k8s GPU plugin).   Only some GPU metrics require extra capabilities (PERFMON), but those should not be needed by normal GPU pods.

[1] For containers wanting to access devices as other than user 0, there are some gotchas, see: https://kubernetes.io/blog/2021/11/09/non-root-containers-and-devices/

**Comment by l1yulong** [comment]
VCACA is end of support.
