### ISSUE TITLE
gst-vaapi plugins don't work on Alder Lake (12th gen)

### ISSUE THREAD

**Issue by omair18** [OpenVisualCloud/Dockerfiles#807]
I am trying to run gst-analytics docker image on Ubuntu20.04LTS but `gst-inspect | grep vaapi`  won't show any output. 

docker run command:  `docker run -it --device /dev/dri --rm openvisualcloud/vcaca-ubuntu2004-analytics-gst:22.3`

![image](https://user-images.githubusercontent.com/1974232/170860645-00b1ca84-2570-4546-a2f5-724219db5996.png)

**Comment by dpatel257** [comment]
Hello @omair18 ,
vaapi is supported on [HW](https://www.intel.com/content/www/us/en/developer/articles/technical/linuxmedia-vaapi.html) where hardware acceleration is present. 

You are using VCAC-A image, Are you running on VCAC-A card?
If not, to use VAAPI, you will need to use Xeon with integrated graphics OR SG1 cards.

Can you share your HW details?

**Comment by l1yulong** [comment]
No longer support VCACA platform.
