### ISSUE TITLE
Missing element: Quicktime demuxer

### ISSUE THREAD

**Issue by zhcf** [OpenVisualCloud/Dockerfiles#812]
use owt-dev image, test mp4 file with the error:  Missing element: Quicktime demuxer

> gst-launch-1.0 filesrc location=/home/test6.mp4 ! decodebin ! autovideosink

Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
WARNING: from element /GstPipeline:pipeline0/GstAutoVideoSink:autovideosink0: Could not open DRM module (NULL)
Additional debug info:
../sys/kms/gstkmssink.c(852): gst_kms_sink_start (): /GstKMSSink:autovideosink0-actual-sink-kms:
reason: No such file or directory (2)
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0: Your GStreamer installation is missing a plug-in.
Missing element: Quicktime demuxer
Additional debug info:
../gst/playback/gstdecodebin2.c(4702): gst_decode_bin_expose (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0:
no suitable plugins found:
Missing decoder: Quicktime (video/quicktime, variant=(string)iso)

ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
ERROR: from element /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstTypeFindElement:typefind: Internal data stream error.
Additional debug info:
../plugins/elements/gsttypefindelement.c(1235): gst_type_find_element_loop (): /GstPipeline:pipeline0/GstDecodeBin:decodebin0/GstTypeFindElement:typefind:
streaming stopped, reason not-linked (-1)
ERROR: pipeline doesn't want to preroll.
Freeing pipeline ...

but I can find the quiktime template using gst-inspect.
> gst-inspect-1.0 video/quicktime
Factory Details:
  Rank                     primary (256)
  Name                     video/quicktime
  Caps                     video/quicktime
  Extensions               mov, mp4

Plugin Details:
  Name                     typefindfunctions
  Description              default typefind functions
  Filename                 /usr/local/lib/gstreamer-1.0/libgsttypefindfunctions.so
  Version                  1.19.1
  License                  LGPL
  Source module            gst-plugins-base
  Source release date      2021-06-01
  Binary package           GStreamer Base Plug-ins source release
  Origin URL               Unknown package origin

**Comment by rpatidar** [comment]
i had very similar problem, my issue was i had a conda environment some half of the commands were getting sourced from it.  on realizing where the commands were picked up find the issues.
