### ISSUE TITLE
Rename docker images for prep to dockerhub submission

### ISSUE THREAD

**Issue by jhou5** [OpenVisualCloud/Dockerfiles#84]

**Comment by jhou5** [comment]
plan is adding the usage segment as part of the image name and a prefix: openvisualcloud.
•	openvisualcloud/xeon-centos76-media-ffmpeg
•	openvisualcloud/xeon-centos76-media-gst
•	openvisualcloud/xeon-centos76-analytics-ffmpeg
•	openvisualcloud/xeon-centos76-analytics-gst
•	openvisualcloud/xeon-centos76-dev
•	openvisualcloud/xeon-centos76-cdn-nginx

**Comment by jhou5** [comment]
@xwu2git would it make sense to create usage segment folder(media, analytics, graphics, dev) under OS folder(i.e centos-7.6) to be aligned with more and more images joined in open visual cloud.

**Comment by xwu2git** [comment]
make sense.

**Comment by jhou5** [comment]
To make it easy to test and code review, would do it separately as I found it is too much code change for this feature.

**Comment by jhou5** [comment]
#108 implemented
